PincardsServer/PincardsServer/Controllers/CardInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PincardsServer.Persistency;

namespace PincardsServer.Controllers
{
    public class CardInfoController : Controller
    {
        private PincardsEntities db = new PincardsEntities();

        // GET: /CardInfo/Create
        public ActionResult Create(long? cardId)
        {
            if (cardId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Card.Find(cardId);
            if (card == null)
            {
                return HttpNotFound();
            }

            CardInfo cardInfo = new CardInfo()
            {
                Key = "-",
                Value = "-",
                Type = "-",
                iPosition = db.CardInfo.Where(i => i.idCardID == cardId).Count(),
                idCardID = cardId
            };

            db.CardInfo.Add(cardInfo);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }

        // POST: /CardInfo/Edit/5
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long idCardInfoID, string key, string value, string type)
        {
            CardInfo info = db.CardInfo.Find(idCardInfoID);
            if (info == null)
            {
                return HttpNotFound();
            }

            info.Key = key;
            info.Value = value;
            info.Type = type;
            db.Entry(info).State = EntityState.Modified;
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }

        // GET: /CardInfo/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardInfo cardinfo = db.CardInfo.Find(id);
            if (cardinfo == null)
            {
                return HttpNotFound();
            }
            cardinfo.iPosition = -1;
            this.Rearrange(cardinfo);
            db.CardInfo.Remove(cardinfo);
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
        }

        private void Rearrange(CardInfo movedInfo)
        {
            long? cardID = movedInfo.idCardID;

            // Alle Infos einer Card außer der verschobenen Info
            IQueryable<CardInfo> infos = db.CardInfo.Where(i => i.idCardID == cardID &&
                i.idCardInfoID != movedInfo.idCardInfoID).OrderBy(i => i.iPosition);

            IEnumerator<CardInfo> it = infos.GetEnumerator();

            int allInfosCount = infos.Count();

            if (movedInfo.iPosition >= 0)
            {
                allInfosCount++;
            }

            for (int i = 0; i < allInfosCount; i++)
            {
                if (i != movedInfo.iPosition)
                {
                    it.MoveNext();
                    it.Current.iPosition = i;
                }
            }
        }

        public ActionResult Move(int? id, string direction)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CardInfo cardinfo = db.CardInfo.Find(id);
            if (cardinfo == null)
            {
                return HttpNotFound();
            }

            if (direction.ToLower().Equals("up"))
            {
                if (cardinfo.iPosition <= 0)
                {
                    return Redirect(Request.UrlReferrer.ToString());
                }
                else if (cardinfo.iPosition == null)
                {
                    cardinfo.iPosition = 0;
                }
                else
                {
                    cardinfo.iPosition--;
                }

                this.Rearrange(cardinfo);
                db.SaveChanges();
            }
            else if (direction.ToLower().Equals("down"))
            {
                int cardInfosCount = cardinfo.Card.CardInfo.Count();

                if (cardinfo.iPosition >= cardInfosCount - 1)
                {
                    return Redirect(Request.UrlReferrer.ToString());
                }
                else if (cardinfo.iPosition == null)
                {
                    cardinfo.iPosition = cardInfosCount - 1;
                }
                else
                {
                    cardinfo.iPosition++;
                }

                this.Rearrange(cardinfo);
                db.SaveChanges();
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PincardsServer/PincardsServer/Controllers/HomeController.cs
using PincardsServer.Persistency;
using PincardsServer.Services;
using RemObjects.SDK;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PincardsServer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ICollection<CardInfo> cardInfo = null;
            User selectedUser = null;
            Card selectedCard = null;
            SelectList cards = null;
            SelectList users = null;

            long userId;
            long.TryParse(Request.QueryString.Get("users"), out userId);

            long cardId;
            long.TryParse(Request.QueryString.Get("cards"), out cardId);

            string searchtype = Request.Form["searchtype"];
            string searchtext = Request.Form["searchtext"];

            using (PincardsEntities db = new PincardsEntities())
            {
                if (!string.IsNullOrWhiteSpace(searchtext))
                {
                    searchtext = searchtext.ToLower().Trim();

                    if (searchtype.Equals("User"))
                    {
                        IQueryable<User> foundUsers = db.User.Where(
                            u => (u.sFirstName != null && u.sFirstName.ToLower().Contains(searchtext)) ||
                                (u.sLastName != null && u.sLastName.ToLower().Contains(searchtext)) ||
                                (u.sMail != null && u.sMail.ToLower().Contains(searchtext)));

                        ViewBag.UserSearchResult = foundUsers.ToList();
                    }
                    else if (searchtype.Equals("Card"))
                    {
                        IQueryable<CardInfo> foundCardInfos = db.CardInfo.Where(
                            i => i.idCardID != null &&
                                (i.Key != null && i.Key.ToLower().Contains(searchtext) ||
                                i.Value != null && i.Value.ToLower().Contains(searchtext) ||
                                i.Type != null && i.Type.ToLower().Contains(searchtext)));

                        ViewBag.CardInfoSearchResult = foundCardInfos.ToList();
                    }
                }

                selectedUser = db.User.Find(userId);
                selectedCard = db.Card.Find(cardId);

                if (selectedUser == null && selectedCard == null)
                {
                    selectedCard = db.Card.FirstOrDefault();
                }

                if (selectedUser == null && selectedCard != null)
                {
                    selectedUser = selectedCard.User;
                }
                else if (selectedUser != null && selectedCard == null)
                {
                    selectedCard = selectedUser.Card.FirstOrDefault();
                }

                if (selectedUser != null)
                {
                    long? selectedCardId = null;
                    if (selectedCard != null)
                    {
                        selectedCardId = selectedCard.idCardID;
                    }
                    cards = new SelectList(selectedUser.Card.OrderBy(c => c.idCardID), "idCardID", "idCardID", selectedCardId);
                    users = new SelectList(db.User.OrderBy(u => u.idUserID).ToList(), "idUserID", "idUserID", selectedUser.idUserID);
                }
                else
                {
                    users = new SelectList(db.User.OrderBy(u => u.idUserID).ToList(), "idUserID", "idUserID");
                }

                if (selectedCard != null)
                {
                    cardInfo = db.CardInfo.Where(i => i.idCardID == selectedCard.idCardID).OrderBy(i => i.iPosition).ToList();
                }

                ViewData["cards"] = cards;
                ViewData["cardInfo"] = cardInfo;
                ViewData["selectedUser"] = selectedUser;
                ViewData["selectedCard"] = selectedCard;
                ViewData["users"] = users;

                return View();
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Test()
        {
            try
            {
                IpHttpClientChannel channel = new IpHttpClientChannel();
                string serverUrl = HttpContext.Request.Url.AbsoluteUri.Substring(0, HttpContext.Request.Url.AbsoluteUri.Length - 9);
                channel.TargetUrl = serverUrl + "Service.ashx/binary";
                ViewBag.Result = CoMainService.Create(new BinMessage(), channel).GetPinById(1);
                //ViewBag.Result = "test result";

                ViewBag.Result += "registerUser: ";
                ViewBag.Result += " - " + CoUserService.Create(new BinMessage(), channel).RegisterUser("test1@test.de", "test");

                ViewBag.Result += "getUserInfo: ";
                var user = CoUserService.Create(new BinMessage(), channel).GetUserInfo(1);
                ViewBag.Result += " - " + user.Email;

                ViewBag.Result += "updateUserInfo: ";
                ViewBag.Result += " - " + CoUserService.Create(new BinMessage(), channel).UpdateUserInfo(
                    new pcUserInfo
                    {
                        UserID = 4,
                        FirstName = "Barney",
                        LastName = "Stinson",
                        Gender = "m",
                        Birthday = DateTime.UtcNow,
                        About = "working at GNB"
                    });

                //ViewBag.Result += "updateProfilePicture: ";
                //ViewBag.Result += " - " + CoUserService.Create(new BinMessage(), channel).UpdateProfilePicture(0, null);

                //ViewBag.Result += "updateWallPicture: ";
                //ViewBag.Result += " - " + CoUserService.Create(new BinMessage(), channel).UpdateWallPicture(0, null);
            }
            catch (Exception e)
            {
                ViewBag.Result = e.Message;
            }
            return View();
        }
    }
}

PincardsServer/PincardsServer/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PincardsServer/PincardsServer/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PincardsServer/PincardsServer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

    var user = ViewData["selectedUser"] as PincardsServer.Persistency.User;
    var card = ViewData["selectedCard"] as PincardsServer.Persistency.Card;
    var cardInfo = ViewData["cardInfo"] as ICollection<PincardsServer.Persistency.CardInfo>;
}

@section head {
    <link rel="stylesheet" type="text/css" href="/Content/Home/Index.css">
    <script type="text/javascript" src="/Scripts/Site.js"></script>
}

<div class="mainContainer">
    <div>
        <div class="searchBar">
            <h5>User</h5>
            @using (Html.BeginForm("Index", "Home", FormMethod.Get))
            {
                @Html.DropDownList("users", null, new { @onchange = "this.form.submit();", @class = "selectList" })
            }
        </div>
        <div class="searchBar">
            <h5>Card</h5>
            @using (Html.BeginForm("Index", "Home", FormMethod.Get))
            {
                @Html.DropDownList("cards", null, new { @onchange = "this.form.submit();", @class = "selectList" })
            }
        </div>
        <div class="searchBar leftMargin">
            <h5>Suche</h5>
            @using (Html.BeginForm("Index", "Home", FormMethod.Post))
            {
                @Html.DropDownList("searchtype", new List<SelectListItem>{
                    new SelectListItem
                    {
                        Text = "User",
                        Value = "User"
                    },
                    new SelectListItem
                    {
                        Text = "Card",
                        Value = "Card"
                    }
                }, new { @class = "selectList" });

                @Html.TextBox("searchtext", "", new { @class = "searchBox" })
            }
        </div>

        <div>
            @if (user != null)
            {
                @Html.ActionLink("Card hinzufügen", "Create", "Card", new { userId = user.idUserID }, null);
            }
            else
            {
                @Html.ActionLink("Card hinzufügen", "Create", "Card");
            }
        </div>
    </div>

    @if (ViewBag.UserSearchResult != null)
    {
        <h4>Suchergebnisse:</h4>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>E-Mail</th>
                <th>Vorname</th>
                <th>Nachname</th>
                <th></th>
            </tr>
            @foreach (var foundUser in ViewBag.UserSearchResult)
            {
                <tr>
                    <td>@foundUser.idUserID</td>
                    <td>@foundUser.sMail</td>
                    <td>@foundUser.sFirstName</td>
                    <td>@foundUser.sLastName</td>
                    <td>@Html.ActionLink("Auswählen", "Index", new { users = foundUser.idUserID })</td>
                </tr>
            }
        </table>
        <a href="javascript:history.go(-1)">Zurück</a>
    }
    else if (ViewBag.CardInfoSearchResult != null)
    {
        <h4>Suchergebnisse:</h4>
        <table class="table">
            <tr>
                <th>CardId</th>
                <th>Schlüssel</th>
                <th>Wert</th>
                <th>Type</th>
                <th></th>
            </tr>

            @foreach (var foundInfo in ViewBag.CardInfoSearchResult)
            {
                <tr>
                    <td>@foundInfo.idCardID</td>
                    <td>@foundInfo.Key</td>
                    <td>@foundInfo.Value</td>
                    <td>@foundInfo.Type</td>
                    <td>@Html.ActionLink("Auswählen", "Index", new { cards = foundInfo.idCardID })</td>
                </tr>
            }
        </table>
        <a href="javascript:history.go(-1)">Zurück</a>
    }
    else
    {
        <div class="topMargin">

            @if (card != null)
            {
                <div class="infoLeft">
                    @card.User.sMail - Card: <b>@card.idCardID</b>
                </div>
                <div class="infoRight">
                    @Html.ActionLink("Bearbeiten", "Edit", "Card", new { id = card.idCardID }, null) |
                    @Html.ActionLink("Löschen", "Delete", "Card", new { id = card.idCardID }, null)
                </div>

                <hr />

                <div class="allImages">
                    <div class="imageDiv">
                        <h5>Card Picture</h5>
                        <img alt="Kein Bild gefunden." class="image" src="@card.sCardPictureUrl" />
                    </div>
                    <div class="imageDiv">
                        <h5>Main Picture</h5>
                        <img alt="Kein Bild gefunden." class="image" src="@card.sMainPictureUrl" />
                    </div>
                    <div class="imageDiv">
                        <h5>Wall Picture</h5>
                        <img alt="Kein Bild gefunden." class="image" src="@card.sWallPictureUrl" />
                    </div>
                </div>

                <div id="addInfoDiv">
                    @Html.ActionLink("Info hinzufügen", "Create", "CardInfo", new { cardId = card.idCardID }, null)
                </div>
            }

            <table class="table">
                <tr class="headerRow">
                    <th>Position</th>
                    <th>Schlüssel</th>
                    <th>Wert</th>
                    <th>Typ</th>
                    <th></th>
                </tr>

                @if (cardInfo != null && cardInfo.Count() > 0)
                {
                    foreach (var info in cardInfo)
                    {
                        <tr>
                            @using (Html.BeginForm("Edit", "CardInfo"))
                            {
                                @Html.AntiForgeryToken()
                                <td>
                                    @info.iPosition | @Html.ActionLink("▲", "Move", "CardInfo", new { id = info.idCardInfoID, direction = "up" }, null)
                                    @Html.ActionLink("▼", "Move", "CardInfo", new { id = info.idCardInfoID, direction = "down" }, null)
                                </td>
                                <td>@Html.TextBox("Key", @info.Key, new { @class = "myTextBox", @onkeydown = "beginEdit(this);" })</td>
                                <td>@Html.TextBox("Value", @info.Value, new { @class = "myTextBox", @onkeydown = "beginEdit(this);" })</td>
                                <td>@Html.TextBox("Type", @info.Type, new { @class = "myTextBox", @onkeydown = "beginEdit(this);" })</td>
                                <td>
                                    @Html.Hidden("idCardInfoID", @info.idCardInfoID)
                                    <input type="submit" value="Speichern" class="submitLink" />|
                                    @Html.ActionLink("Löschen", "Delete", "CardInfo", new { id = info.idCardInfoID }, null)
                                </td>
                            }
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Keine Daten vorhanden.</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                }
            </table>

        </div>
    }
</div>

PincardsServer/PincardsServer/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>


@ViewBag.Result