PincardsServer/PincardsServer/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PincardsServer.Persistency;
using System.IO;
using System.Drawing;

namespace PincardsServer.Controllers
{
    public class CardController : Controller
    {
        private PincardsEntities db = new PincardsEntities();

        // GET: /Card/
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        // GET: /Card/Create
        public ActionResult Create(long? userId)
        {
            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.User.Find(userId);
            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.idUserID = new SelectList(db.User, "idUserID", "sMail", user.idUserID);
            return View();
        }

        // POST: /Card/Create
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idCardID, idUserID")] Card card, HttpPostedFileBase wallPicture, HttpPostedFileBase mainPicture, HttpPostedFileBase cardPicture)
        {
            if (ModelState.IsValid)
            {
                db.Card.Add(card);
                db.SaveChanges();
                StoreCardPictures(card, wallPicture, mainPicture, cardPicture);
                return RedirectToAction("Index", "Home", new { cards = card.idCardID });
            }

            ViewBag.idUserID = new SelectList(db.User, "idUserID", "sMail", card.idUserID);
            return View(card);
        }

        // GET: /Card/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Card.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            ViewBag.idUserID = new SelectList(db.User, "idUserID", "sMail", card.idUserID);
            return View(card);
        }

        // POST: /Card/Edit/5
        // Aktivieren Sie zum Schutz vor übermäßigem Senden von Angriffen die spezifischen Eigenschaften, mit denen eine Bindung erfolgen soll. Weitere Informationen 
        // finden Sie unter http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long idCardID, long? idUserID, HttpPostedFileBase wallPicture, HttpPostedFileBase mainPicture, HttpPostedFileBase cardPicture)
        {
            Card card = db.Card.Find(idCardID);
            if (card == null)
            {
                return HttpNotFound();
            }

            card.idUserID = idUserID;
            StoreCardPictures(card, wallPicture, mainPicture, cardPicture);
            db.Entry(card).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "Home", new { cards = card.idCardID });
        }

        // GET: /Card/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Card card = db.Card.Find(id);
            if (card == null)
            {
                return HttpNotFound();
            }
            return View(card);
        }

        // POST: /Card/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Card card = db.Card.Find(id);
            long? userId = card.idUserID;

            db.CardInfo.RemoveRange(card.CardInfo);
            db.Card.Remove(card);
            db.SaveChanges();
            Storage.DeleteCardPictures(id);
            return RedirectToAction("Index", "Home", new { users = userId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void StoreCardPictures(Card card, HttpPostedFileBase wallPicture, HttpPostedFileBase mainPicture, HttpPostedFileBase cardPicture)
        {
            if (cardPicture != null && cardPicture.ContentLength > 0 && cardPicture.ContentType == "image/png")
            {
                // Höhe und Breite abspeichern.
                using (Image image = Image.FromStream(cardPicture.InputStream))
                {
                    card.iCardPictureHeight = (short)image.Height;
                    card.iCardPictureWidth = (short)image.Width;
                }

                cardPicture.InputStream.Position = 0;

                // Bild abspeichern.
                using (MemoryStream stream = new MemoryStream())
                {
                    cardPicture.InputStream.CopyTo(stream);
                    stream.Flush();
                    stream.Position = 0;
                    card.sCardPictureUrl = Storage.UploadCardCardPicture(card.idCardID, stream);
                }

                db.SaveChanges();
            }

            if (mainPicture != null && mainPicture.ContentLength > 0 && mainPicture.ContentType == "image/png")
            {
                // Höhe und Breite abspeichern.
                using (Image image = Image.FromStream(mainPicture.InputStream))
                {
                    card.iMainPictureHeight = (short)image.Height;
                    card.iMainPictureWidth = (short)image.Width;
                }

                mainPicture.InputStream.Position = 0;

                // Bild abspeichern.
                using (MemoryStream stream = new MemoryStream())
                {
                    mainPicture.InputStream.CopyTo(stream);
                    stream.Flush();
                    stream.Position = 0;
                    card.sMainPictureUrl = Storage.UploadCardMainPicture(card.idCardID, stream);
                }

                db.SaveChanges();
            }

            if (wallPicture != null && wallPicture.ContentLength > 0 && wallPicture.ContentType == "image/png")
            {
                // Höhe und Breite abspeichern.
                using (Image image = Image.FromStream(wallPicture.InputStream, true, true))
                {
                    card.iWallPictureHeight = (short)image.Height;
                    card.iWallPictureWidth = (short)image.Width;
                }

                wallPicture.InputStream.Position = 0;

                // Bild abspeichern.
                using (MemoryStream stream = new MemoryStream())
                {
                    wallPicture.InputStream.CopyTo(stream);
                    stream.Flush();
                    stream.Position = 0;
                    card.sWallPictureUrl = Storage.UploadCardWallPicture(card.idCardID, stream);
                }

                db.SaveChanges();
            }
        }
    }
}

PincardsServer/PincardsServer/Views/Card/Create.cshtml
@model PincardsServer.Persistency.Card

@{
    ViewBag.Title = "Create";
}

<h2>Erstellen</h2>

@using (Html.BeginForm("Create", "Card", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Card</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.idUserID, "User", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUserID", String.Empty)
                @Html.ValidationMessageFor(model => model.idUserID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sCardPictureUrl, "Card Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="cardPicture" name="cardPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sMainPictureUrl, "Main Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="mainPicture" name="mainPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sWallPictureUrl, "Wall Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="wallPicture" name="wallPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.go(-1)">Zurück zur Übersicht</a>
</div>

PincardsServer/PincardsServer/Views/Card/Delete.cshtml
@model PincardsServer.Persistency.Card

@{
    ViewBag.Title = "Delete";
}

<style type="text/css">
    .deleteImage {
        max-width: 100%;
        max-height: 100px;
    }
</style>

<h2>Löschen</h2>

<h3>Wollen Sie diese Karte wirklich löschen?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Wall Picture")
        </dt>

        <dd>
            <img src="@Model.sWallPictureUrl" alt="Kein Bild gefunden." class="deleteImage" />
        </dd>

        <dt>
            @Html.DisplayName("Card Picture")
        </dt>

        <dd>
            <img src="@Model.sCardPictureUrl" alt="Kein Bild gefunden." class="deleteImage" />
        </dd>

        <dt>
            @Html.DisplayName("Main Picture")
        </dt>

        <dd>
            <img src="@Model.sMainPictureUrl" alt="Kein Bild gefunden." class="deleteImage" />
        </dd>

        <dt>
            @Html.DisplayName("User")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.sMail)
        </dd>

    </dl>

    <table class="table">
        <tr>
            <td>Schlüssel</td>
            <td>Wert</td>
            <td>Type</td>
        </tr>

        @if (Model.CardInfo.Count > 0)
        {
            foreach (var info in Model.CardInfo)
            {
                <tr>
                    <td>@info.Key</td>
                    <td>@info.Value</td>
                    <td>@info.Type</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>Keine Daten vorhanden.</td>
                <td></td>
                <td></td>
            </tr>
        }
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-default" /> |
            <a href="javascript:history.go(-1)">Zurück zur Übersicht</a>
        </div>
    }
</div>

PincardsServer/PincardsServer/Views/Card/Edit.cshtml
@model PincardsServer.Persistency.Card

@{
    ViewBag.Title = "Edit";
}

<h2>Bearbeiten</h2>

@using (Html.BeginForm("Edit", "Card", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Card</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.idCardID)

        <div class="form-group">
            @Html.LabelFor(model => model.idUserID, "User", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUserID", String.Empty)
                @Html.ValidationMessageFor(model => model.idUserID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sCardPictureUrl, "Card Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="cardPicture" name="cardPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sMainPictureUrl, "Main Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="mainPicture" name="mainPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sWallPictureUrl, "Wall Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="wallPicture" name="wallPicture" accept="image/png" class='input' />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="javascript:history.go(-1)">Zurück zur Übersicht</a>
</div>